// Previous Year Grand Finale Teams DATA
const previousYearGrandFinaleTeamsAPI = [
  {
    id: 1,
    PSID: "PS-1",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 1",
    collage: "Collage Name",
  },
  {
    id: 2,
    PSID: "PS-2",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 2",
    collage: "Collage Name",
  },
  {
    id: 3,
    PSID: "PS-3",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 3",
    collage: "Collage Name",
  },
  {
    id: 4,
    PSID: "PS-4",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 4",
    collage: "Collage Name",
  },
  {
    id: 5,
    PSID: "PS-5",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 5",
    collage: "Collage Name",
  },
  {
    id: 6,
    PSID: "PS-6",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 6",
    collage: "Collage Name",
  },
  {
    id: 7,
    PSID: "PS-7",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 7",
    collage: "Collage Name",
  },
  {
    id: 8,
    PSID: "PS-8",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 8",
    collage: "Collage Name",
  },
  {
    id: 9,
    PSID: "PS-9",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 9",
    collage: "Collage Name",
  },
  {
    id: 10,
    PSID: "PS-10",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 10",
    collage: "Collage Name",
  },
  {
    id: 11,
    PSID: "PS-11",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 11",
    collage: "Collage Name",
  },
  {
    id: 12,
    PSID: "PS-12",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 12",
    collage: "Collage Name",
  },
  {
    id: 13,
    PSID: "PS-13",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 13",
    collage: "Collage Name",
  },
  {
    id: 14,
    PSID: "PS-14",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 14",
    collage: "Collage Name",
  },
  {
    id: 15,
    PSID: "PS-15",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 15",
    collage: "Collage Name",
  },
  {
    id: 16,
    PSID: "PS-16",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 16",
    collage: "Collage Name",
  },
  {
    id: 17,
    PSID: "PS-17",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 17",
    collage: "Collage Name",
  },
  {
    id: 18,
    PSID: "PS-18",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 18",
    collage: "Collage Name",
  },
  {
    id: 19,
    PSID: "PS-19",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 19",
    collage: "Collage Name",
  },
  {
    id: 20,
    PSID: "PS-20",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 20",
    collage: "Collage Name",
  },
  {
    id: 21,
    PSID: "PS-21",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 21",
    collage: "Collage Name",
  },
  {
    id: 22,
    PSID: "PS-22",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 22",
    collage: "Collage Name",
  },
  {
    id: 1,
    PSID: "PS-1",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 1",
    collage: "Collage Name",
  },
  {
    id: 23,
    PSID: "PS-23",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 23",
    collage: "Collage Name",
  },
  {
    id: 24,
    PSID: "PS-24",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 24",
    collage: "Collage Name",
  },
  {
    id: 25,
    PSID: "PS-25",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 25",
    collage: "Collage Name",
  },
  {
    id: 26,
    PSID: "PS-26",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 26",
    collage: "Collage Name",
  },
  {
    id: 27,
    PSID: "PS-27",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 27",
    collage: "Collage Name",
  },
  {
    id: 28,
    PSID: "PS-28",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 28",
    collage: "Collage Name",
  },
  {
    id: 29,
    PSID: "PS-29",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 29",
    collage: "Collage Name",
  },
  {
    id: 30,
    PSID: "PS-30",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 30",
    collage: "Collage Name",
  },
];

// Previous Year Winners DATA
const previousYearWinnersAPI = [
  {
    id: 1,
    PSID: "PS-1",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 1",
    collage: "Collage Name",
  },
  {
    id: 2,
    PSID: "PS-2",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 2",
    collage: "Collage Name",
  },
  {
    id: 3,
    PSID: "PS-3",
    teamName: "Team Name",
    teamLeaderName: "Team Leader Name",
    organization: "Organization Name",
    PSCategory: "Software/Website/Hardware",
    problemStatement: "Problem Statement 3",
    collage: "Collage Name",
  },
];

export { previousYearGrandFinaleTeamsAPI, previousYearWinnersAPI };
