const patronsGalleryAPI = [
  {
    id: 1,
    photo: "./images/gallery/1.jpg",
    name: "Mr. Siddharth Agrawal",
    bio: "MD, Sagar Group",
    linkedInProfile: "",
    twitterProfile: "",
    instagramProfile: "",
    facebookProfile: "",
  },
  {
    id: 2,
    photo: "./images/gallery/2.jpg",
    name: "Dr. Jyoti Deshmukh",
    bio: "Group Director at SISTec",
    linkedInProfile: "",
    twitterProfile: "",
    instagramProfile: "",
    facebookProfile: "",
  },
  {
    id: 3,
    photo: "./images/gallery/3.jpg",
    name: "Dr. Manish Billore",
    bio: "Principal of SISTec-E",
    linkedInProfile: "",
    twitterProfile: "",
    instagramProfile: "",
    facebookProfile: "",
  },
  {
    id: 4,
    photo: "./images/gallery/1.jpg",
    name: "Mr. Siddharth Agrawal",
    bio: "MD, Sagar Group",
    linkedInProfile: "",
    twitterProfile: "",
    instagramProfile: "",
    facebookProfile: "",
  },
  {
    id: 5,
    photo: "./images/gallery/2.jpg",
    name: "Dr. Jyoti Deshmukh",
    bio: "Group Director at SISTec",
    linkedInProfile: "",
    twitterProfile: "",
    instagramProfile: "",
    facebookProfile: "",
  },
  {
    id: 6,
    photo: "./images/gallery/3.jpg",
    name: "Dr. Manish Billore",
    bio: "Principal of SISTec-E",
    linkedInProfile: "",
    twitterProfile: "",
    instagramProfile: "",
    facebookProfile: "",
  },
];

export default patronsGalleryAPI;
