const problemStatementsAPI = [
  {
    id: 1,
    organization: "Organization name",
    problemStatement: "Problem Statement 1",
    category: "Software/Website",
    PSNumber: "PS-1",
    domainBucket: "Theme Name",
  },
  {
    id: 2,
    organization: "Organization name",
    problemStatement: "Problem Statement 2",
    category: "Software/Website",
    PSNumber: "PS-2",
    domainBucket: "Theme Name",
  },
  {
    id: 3,
    organization: "Organization name",
    problemStatement: "Problem Statement 3",
    category: "Software/Website",
    PSNumber: "PS-3",
    domainBucket: "Theme Name",
  },
  {
    id: 4,
    organization: "Organization name",
    problemStatement: "Problem Statement 4",
    category: "Software/Website",
    PSNumber: "PS-4",
    domainBucket: "Theme Name",
  },
  {
    id: 5,
    organization: "Organization name",
    problemStatement: "Problem Statement 5",
    category: "Software/Website",
    PSNumber: "PS-5",
    domainBucket: "Theme Name",
  },
  {
    id: 6,
    organization: "Organization name",
    problemStatement: "Problem Statement 6",
    category: "Software/Website",
    PSNumber: "PS-6",
    domainBucket: "Theme Name",
  },
  {
    id: 7,
    organization: "Organization name",
    problemStatement: "Problem Statement 7",
    category: "Software/Website",
    PSNumber: "PS-7",
    domainBucket: "Theme Name",
  },
  {
    id: 8,
    organization: "Organization name",
    problemStatement: "Problem Statement 8",
    category: "Software/Website",
    PSNumber: "PS-8",
    domainBucket: "Theme Name",
  },
  {
    id: 9,
    organization: "Organization name",
    problemStatement: "Problem Statement 9",
    category: "Software/Website",
    PSNumber: "PS-9",
    domainBucket: "Theme Name",
  },
  {
    id: 10,
    organization: "Organization name",
    problemStatement: "Problem Statement 10",
    category: "Software/Website",
    PSNumber: "PS-10",
    domainBucket: "Theme Name",
  },
];

export default problemStatementsAPI;